//! scb-submit unit tests — cross-language fixture + dry-run smoke.
//!
//! The intent vector is generated by the Rust runner
//! (runner/src/intent.rs :: dump_intent_vector) and committed at
//! test-vectors/intent_v1.json so TS byte-equality is provable.

import { test } from "node:test";
import assert from "node:assert/strict";
import * as fs from "fs";
import * as os from "os";
import * as path from "path";
import { execFileSync } from "child_process";

import {
  buildIntentMessage,
  sha256,
  encodeSubmitExploitData,
  parseUploadResponse,
  submissionReference,
  validateExploitZip,
} from "../submit-lib";

function repoRoot(): string {
  let dir = __dirname;
  for (let i = 0; i < 6; i++) {
    if (fs.existsSync(path.join(dir, ".git"))) return dir;
    dir = path.dirname(dir);
  }
  throw new Error("repo root not found");
}

interface IntentVector {
  intent_tag_ascii: string;
  bounty_pda_hex: string;
  plaintext_sha256_hex: string;
  solver_secret_seed_hex: string;
  message_hex: string;
  signature_b64: string;
}

function loadVector(): IntentVector {
  const p = path.resolve(repoRoot(), "test-vectors/intent_v1.json");
  return JSON.parse(fs.readFileSync(p, "utf8"));
}

test("(IV) TS intent builder reproduces the Rust golden vector", () => {
  const v = loadVector();
  const msg = buildIntentMessage(
    Buffer.from(v.bounty_pda_hex, "hex"),
    Buffer.from(v.plaintext_sha256_hex, "hex")
  );
  assert.equal(msg.length, 77);
  assert.equal(msg.toString("hex"), v.message_hex);

  // Signature cross-check: same seed must produce the same ed25519 sig.
  // tweetnacl derives the keypair from the 32-byte seed directly.
  const pair = require("tweetnacl").sign.keyPair.fromSeed(
    Uint8Array.from(Buffer.from(v.solver_secret_seed_hex, "hex"))
  );
  const sig = require("tweetnacl").sign.detached(new Uint8Array(msg), pair.secretKey);
  assert.equal(Buffer.from(sig).toString("base64"), v.signature_b64);
});

test("(IVb) sha256 helper matches node crypto for the fixture plaintext", () => {
  const v = loadVector();
  const pt = Buffer.from("exploit");
  assert.equal(sha256(pt).toString("hex"), v.plaintext_sha256_hex);
});

test("upload receipt is encoded independently of the plaintext hash", () => {
  const receipt = "0123456789abcdef".repeat(4);
  assert.deepEqual(parseUploadResponse({ receipt }), { receipt });
  const reference = submissionReference(receipt);
  assert.equal(reference, `scb:submission:v1:${receipt}`);
  assert.equal(reference.length, 82);
  const plaintextSha = sha256(Buffer.from("exploit"));
  const instruction = encodeSubmitExploitData(7n, reference, plaintextSha);
  assert.equal(instruction.readUInt32LE(16), 82);
  assert.equal(instruction.subarray(20, 102).toString("utf8"), reference);
  assert.deepEqual(instruction.subarray(102), plaintextSha);
});

test("malformed or legacy upload responses cannot produce a submission reference", () => {
  const receipt = "a".repeat(64);
  for (const value of [
    null, undefined, [], "receipt", {}, { blob_url: receipt },
    { receipt, blob_url: "https://example.com/upload" },
    { receipt: 42 }, { receipt: "" }, { receipt: "a".repeat(63) },
    { receipt: "a".repeat(65) }, { receipt: "A".repeat(64) },
    { receipt: "g".repeat(64) }, { receipt: `${receipt}\n` },
    { receipt: `scb:submission:v1:${receipt}` },
    { receipt: `https://example.com/${receipt}` },
  ]) {
    assert.throws(() => parseUploadResponse(value), /invalid upload receipt/);
  }
});

test("exploit ZIP client guard enforces size and ZIP signatures", () => {
  assert.doesNotThrow(() => validateExploitZip(Uint8Array.from([0x50, 0x4b, 0x03, 0x04])));
  assert.throws(() => validateExploitZip(Uint8Array.from([0x23, 0x21, 0x2f, 0x62])), /ZIP archive/);
  assert.throws(
    () => validateExploitZip(Uint8Array.from([0x50, 0x4b, 0x03, 0x04, ...new Array(9_000).fill(0)])),
    /9000 byte limit/,
  );
});

test("(T-DRY) dry-run prints payload shapes without network", () => {
  const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "scb-submit-test-"));
  const zipPath = path.join(tempDir, "exploit.zip");
  // The client reads and seals exact ZIP bytes; the runner validates contents.
  fs.writeFileSync(
    zipPath,
    Buffer.from(
      "UEsDBBQAAAAIAOlbSV0Yn9XvDwAAAA0AAAAKAAAAZXhwbG9pdC5weSsoyswr0VBKy0lMV9IEAFBLAQIUAxQAAAAIAOlbSV0Yn9XvDwAAAA0AAAAKAAAAAAAAAAAAAACAAQAAAABleHBsb2l0LnB5UEsFBgAAAAABAAEAOAAAADcAAAAAAA==",
      "base64",
    ),
  );
  try {
    const out = execFileSync(
      process.execPath,
      [
        path.resolve(__dirname, "../scb-submit.js"),
        "--rpc-url",
        "http://127.0.0.1:8899",
        "--keypair",
        path.resolve(__dirname, "../../src/test/fixture-keypair.json"),
        "--bounty",
        `${"11111111111111111111111111111111"}:7`,
        "--file",
        zipPath,
        "--enclave-url",
        "http://127.0.0.1:8443",
        "--dry-run",
      ],
      { encoding: "utf8" }
    );
    assert.match(out, /exploit_sealed_box_b64_len/);
    assert.match(out, /submit_intent_sig_b64_len/);
    assert.match(out, /submit_exploit data length: 134/);
  } finally {
    fs.rmSync(tempDir, { recursive: true, force: true });
  }
});
