//! scb-submit unit tests — cross-language fixture + dry-run smoke.
//!
//! The intent vector is generated by the Rust runner
//! (runner/src/intent.rs :: dump_intent_vector) and committed at
//! test-vectors/intent_v1.json so TS byte-equality is provable.

import { test } from "node:test";
import assert from "node:assert/strict";
import * as fs from "fs";
import * as path from "path";
import { execFileSync } from "child_process";

import {
  buildIntentMessage,
  sha256,
  encodeSubmitExploitData,
} from "../submit-lib";

function repoRoot(): string {
  let dir = __dirname;
  for (let i = 0; i < 6; i++) {
    if (fs.existsSync(path.join(dir, ".git"))) return dir;
    dir = path.dirname(dir);
  }
  throw new Error("repo root not found");
}

interface IntentVector {
  intent_tag_ascii: string;
  bounty_pda_hex: string;
  plaintext_sha256_hex: string;
  solver_secret_seed_hex: string;
  message_hex: string;
  signature_b64: string;
}

function loadVector(): IntentVector {
  const p = path.resolve(repoRoot(), "test-vectors/intent_v1.json");
  return JSON.parse(fs.readFileSync(p, "utf8"));
}

test("(IV) TS intent builder reproduces the Rust golden vector", () => {
  const v = loadVector();
  const msg = buildIntentMessage(
    Buffer.from(v.bounty_pda_hex, "hex"),
    Buffer.from(v.plaintext_sha256_hex, "hex")
  );
  assert.equal(msg.length, 77);
  assert.equal(msg.toString("hex"), v.message_hex);

  // Signature cross-check: same seed must produce the same ed25519 sig.
  // tweetnacl derives the keypair from the 32-byte seed directly.
  const pair = require("tweetnacl").sign.keyPair.fromSeed(
    Uint8Array.from(Buffer.from(v.solver_secret_seed_hex, "hex"))
  );
  const sig = require("tweetnacl").sign.detached(new Uint8Array(msg), pair.secretKey);
  assert.equal(Buffer.from(sig).toString("base64"), v.signature_b64);
});

test("(IVb) sha256 helper matches node crypto for the fixture plaintext", () => {
  const v = loadVector();
  const pt = Buffer.from("exploit");
  assert.equal(sha256(pt).toString("hex"), v.plaintext_sha256_hex);
});

test("(T-DRY) dry-run prints payload shapes without network", () => {
  const out = execFileSync(
    process.execPath,
    [
      path.resolve(__dirname, "../scb-submit.js"),
      "--rpc-url",
      "http://127.0.0.1:8899",
      "--keypair",
      path.resolve(__dirname, "../../src/test/fixture-keypair.json"),
      "--bounty",
      `${"11111111111111111111111111111111"}:7`,
      "--file",
      path.resolve(__dirname, "../../src/test/fixture-exploit.py"),
      "--enclave-url",
      "http://127.0.0.1:8443",
      "--dry-run",
    ],
    { encoding: "utf8" }
  );
  assert.match(out, /exploit_sealed_box_b64_len/);
  assert.match(out, /submit_intent_sig_b64_len/);
});
