import type { Manifest } from "./manifest";

/** docker Architecture -> setarch machine name. */
function machineOf(arch: string): string {
  switch (arch) {
    case "amd64":
    case "x86_64":
      return "x86_64";
    case "arm64":
    case "aarch64":
      return "aarch64";
    default:
      return arch;
  }
}

const CONTRACT_HEADER = (m: Manifest, machine: string, origTokens: string[]) => {
  const base = [...m.entrypoint ? [] : []]; // placeholder to keep shape explicit
  void base;
  return `# -----------------------------------------------------------------------------
# SealedCodeBounty DEV PLANE (generated by scb-pack — deterministic output)
#
# VERIFIER PARITY CONTRACT (BUILD_PLAN_v2.md §4.5 / D13):
#   The verification enclave spawns this EXACT image with this EXACT command,
#   including the setarch personality prefix below when determinism.aslr=off.
#   Anything that works against 'target' inside this compose network MUST
#   reproduce identically in the single verification run:
#     spawn = ["setarch", "${machine}", "-R"] + ${JSON.stringify(origTokens)}
#   and SEED=${m.determinism.seed} is exported to the process environment.
#   Do not edit by hand — regenerate with scb-pack.
# -----------------------------------------------------------------------------`;
};

/** Word-wraps a single logical line into <=max chunks (folded-scalar safe). */
function chunkLine(s: string, max: number): string[] {
  const words = s.split(" ");
  const out: string[] = [];
  let cur = "";
  for (const w of words) {
    if (cur && (cur + " " + w).length > max) {
      out.push(cur);
      cur = w;
    } else {
      cur = cur ? `${cur} ${w}` : w;
    }
  }
  if (cur) out.push(cur);
  return out;
}

export function renderCompose(
  m: Manifest,
  imageTag: string,
  imageArch: string,
  origEntrypoint: string[],
  origCmd: string[]
): string {
  const machine = machineOf(imageArch);
  const origTokens = [...origEntrypoint, ...origCmd];
  const lines: string[] = [];

  lines.push(CONTRACT_HEADER(m, machine, origTokens));
  lines.push("services:");

  // ---- target -----------------------------------------------------------
  lines.push("  target:");
  lines.push(`    image: ${imageTag}`);
  lines.push("    networks:");
  lines.push("      scbnet: {}");
  if (m.determinism.aslr === "off") {
    if (origTokens.length === 0) {
      // Caller validated earlier; defensive line keeps generated file honest.
      lines.push("    command: [\"sleep\", \"infinity\"] # NOTE: image had no entrypoint/cmd");
    } else {
      lines.push("    entrypoint:");
      lines.push("      - /bin/sh");
      lines.push("      - -c");
      lines.push(`      - exec setarch ${machine} -R "$@"`);
      lines.push("      - --");
      for (const tok of origTokens) {
        lines.push(`      - ${JSON.stringify(tok)}`);
      }
    }
  }
  if (m.target.kind === "tcp_service") {
    lines.push("    expose:");
    lines.push(`      - "${m.target.port}"`);
  }
  lines.push("    environment:");
  lines.push(`      SEED: "${m.determinism.seed}"`);
  lines.push("      FLAG_FILE: /flag");

  // ---- workspace --------------------------------------------------------
  lines.push("  workspace:");
  lines.push("    image: ubuntu:24.04");
  lines.push("    depends_on:");
  lines.push("      - target");
  lines.push("    networks:");
  lines.push("      scbnet: {}");
  lines.push("      default: {}");
  lines.push("    ports:");
  lines.push('      - "7681:7681"');
  lines.push("    entrypoint:");
  lines.push("      - /bin/bash");
  lines.push("      - -lc");
  // Folded block scalar keeps the long bootstrap readable AND valid YAML.
  const boot = [
    "apt-get update",
    "DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tmux python3 python3-pip ttyd netcat-openbsd socat gdb strace ltrace",
    "pip install pwntools --break-system-packages",
    "echo '[scb] workspace ready - pwntools installed; target reachable as host target'",
    "ttyd -W bash",
  ].join(" && ");
  lines.push("      - >-");
  for (const chunk of chunkLine(boot, 100)) {
    lines.push(`        ${chunk}`);
  }

  // Audit M3: 'internal: true' = loopback-only fabric. The target has NO
  // internet egress; only the workspace touches the outside world for tooling.
  lines.push("networks:");
  lines.push("  scbnet:");
  lines.push("    driver: bridge");
  lines.push("    internal: true");
  lines.push("  default: {}");
  lines.push("");
  return lines.join("\n");
}
